### ISSUE TITLE
Selector hides all `footer` elements when printed

### ISSUE THREAD

**Issue by fofr** [alphagov/govuk_template#279] opened 2017-03-07 10:01 UTC
There's a CSS rule to hide the footer when printing, but it uses element selectors to determine what to hide:
https://github.com/alphagov/govuk_template/blob/master/source/assets/stylesheets/_core-print.scss#L76-L77

This assumes that all `footer` elements contain information that is not worth printing. That can't be guaranteed.

```css
body footer {
  display: none !important;
}
```

**Comment by robinwhittleton** [comment] 2017-03-07 10:55
Duplicate of https://github.com/alphagov/govuk_template/issues/64

**Closed by robinwhittleton** 2017-03-07 10:55 UTC
